### ISSUE TITLE
How deploy storm cluster with many supervisor through docker-compose

### ISSUE THREAD

**Issue by IvanBiv** [31z4/storm-docker#16]
We want to deploy apache-storm as cluster in cluster hosts. More precisely we need have supervisor instances in all host-nodes. How we can deploy storm cluster with docker-compose file? We have docker-compose.yml file:

```
version: "3.6"
services:
    zookeeper:
        image: zookeeper
        networks:
          - esnet1
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
    nimbus:
        image: storm
        command: storm nimbus
        volumes:
            - logs:/logs
        depends_on:
            - zookeeper
        networks:
          - esnet1
        ports:
            - 6627:6627
        deploy:
            restart_policy:
                condition: on-failure
    supervisor:
        image: storm
        command: storm supervisor -c storm.log.dir="/logs"
        depends_on:
            - nimbus
            - zookeeper
            - elasticsearch
        networks:
          - esnet1
#        volumes:
#          - type: bind
#            source: /data/storm
#            target: /data
#          - type: volume
#            source: logs
#            target: /logs
        deploy:
            mode: global
#            replicas: 1
            placement:
                constraints:
                  - node.labels.processor==true
            restart_policy:
                condition: on-failure
    ui:
        image: storm
        command: storm ui -c storm.log.dir="/logs"
        volumes:
            - logs:/log
        networks:
          - esnet1
        depends_on:
            - nimbus
        ports:
            - 8081:8080
        deploy:
            restart_policy:
                condition: on-failure
networks:
  esnet1:
    attachable: true
volumes:
    logs:
```
than we see next log in supervisor service:
```
Running: /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -server -Ddaemon.name=supervisor -Dstorm.options=storm.log.dir%3D%2Flogs -Dstorm.home=/apache-storm-1.2.1 -Dstorm.log.dir=/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /apache-storm-1.2.1/*:/apache-storm-1.2.1/lib/*:/apache-storm-1.2.1/extlib/*:/apache-storm-1.2.1/extlib-daemon/*:/conf -Xmx256m -Dlogfile.name=supervisor.log -Dlog4j.configurationFile=/apache-storm-1.2.1/log4j2/cluster.xml org.apache.storm.daemon.supervisor.Supervisor
standard_init_linux.go:190: exec user process caused "exec format error"
```
If we made next change in docker-compose.yml:
```
supervisor:
...
        deploy:
#            mode: global
            replicas: 1
...
```
than cluster deployed.
How we can deploy Storm cluster through docker-compose?
