### ISSUE TITLE
exemplary docker-compose from README not working.

### ISSUE THREAD

**Issue by marta-tatiana** [31z4/storm-docker#2]
Hi,
I tried to use your images with docker-compose you provide in README.
It seems to me that is it not enough to make containers dependent on each other, they must also link each other. Also, I had to change "nimbus.host" and "storm.zookeeper.servers" to the names of containers (which, in my case, are networkname_nimbus_1, networkname_supervisor_1 etc. and not the names of entries from docker-compose). Using docker-compose 1.7.0 and Docker 1.11.1 on Windows 7 host. I wonder if the naming convention depends on Docker version?

I got it working with sth like (docker-compose.yml placed in 'storm' directory):

```
version: '2'
services:
    zookeeper:
        image: 31z4/zookeeper:3.4.8
        restart: always

    nimbus:
        image: 31z4/storm:1.0.2
        command: storm nimbus -c storm.zookeeper.servers="[\"storm_zookeeper_1\"]" -c nimbus.host="storm_nimbus_1"
        links:
            - zookeeper
        depends_on:
            - zookeeper
        restart: always
        ports:
            - 6627:6627

    supervisor:
        image: 31z4/storm:1.0.2
        command: storm supervisor -c storm.zookeeper.servers="[\"storm_zookeeper_1\"]" -c nimbus.host="storm_nimbus_1"
        links:
            - nimbus
            - zookeeper
        depends_on:
            - nimbus
            - zookeeper
        restart: always

```

Those images are needed, I hope they will soon become official ones :)

Edit: just learned that container names can be set with "container_name". That solves the problem with names dependent on parent directory.
