### ISSUE TITLE
how should start a cluster with 3 nimbus and 3 supervisors?

### ISSUE THREAD

**Issue by jiucai** [31z4/storm-docker#8]
I wrote docker-compose.yml, and started it, bus I found there is only 1 supervisor in storm ui:

![storm-ui](https://cloud.githubusercontent.com/assets/610289/21542379/40749c6e-cdf8-11e6-906f-5c71248a0f11.png)

my docker-compose.yml

> 
version: '2'
services:
    zoo1:
        image: zookeeper
        hostname: zoo1
        container_name: zoo1
        ports:
           - "2181"
        restart: always
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        volumes:
            - /docker/app/zookeeper/zoo1-log:/datalog
            - /docker/app/zookeeper/zoo1-data:/data
    zoo2:
        image: zookeeper
        hostname: zoo2
        container_name: zoo2
        ports:
           - "2181"
        restart: always
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        volumes:
            - /docker/app/zookeeper/zoo2-log:/datalog
            - /docker/app/zookeeper/zoo2-data:/data
    zoo3:
        image: zookeeper
        hostname: zoo3
        container_name: zoo3
        ports:
           - "2181"
        restart: always
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        volumes:
            - /docker/app/zookeeper/zoo3-log:/datalog
            - /docker/app/zookeeper/zoo3-data:/data
    nimbus1:
        image: storm
        hostname: nimbus1
        container_name: nimbus1
        command: storm nimbus
        depends_on:
            - zoo1
            - zoo2
            - zoo3
        links:
            - zoo1:zookeeper
            - zoo2:zookeeper
            - zoo3:zookeeper
        restart: always
        #ports:
        #    - "6627:6627"
        volumes:
            - /docker/app/storm/logs:/logs
            - /docker/app/storm/data:/data
    nimbus2:
        image: storm
        hostname: nimbus2
        container_name: nimbus2
        command: storm nimbus
        depends_on:
            - zoo1
            - zoo2
            - zoo3
        links:
            - zoo1:zookeeper
            - zoo2:zookeeper
            - zoo3:zookeeper
        restart: always
        #ports:
        #    - "6627:6627"
        volumes_from:
            - nimbus1
    nimbus3:
        image: storm
        hostname: nimbus3
        container_name: nimbus3
        command: storm nimbus
        depends_on:
            - zoo1
            - zoo2
            - zoo3
        links:
            - zoo1:zookeeper
            - zoo2:zookeeper
            - zoo3:zookeeper
        restart: always
        #ports:
        #    - "6627:6627"
        volumes_from:
            - nimbus1
    ui:
        image: storm
        #hostname: ui1
        container_name: ui
        command: storm ui
        depends_on:
            - nimbus1
            - nimbus2
            - nimbus3
        links:
            - nimbus1:nimbus
            - nimbus2:nimbus
            - nimbus3:nimbus
        restart: always
        ports:
             - "8001:8080"
        volumes_from:
            - nimbus1
    supervisor1:
        image: storm
        hostname: supervisor1
        container_name: supervisor1
        command: storm supervisor -c nimbus.host=nimbus1,nimbus2,nimbus3
        depends_on:
            - nimbus1
            - nimbus2
            - nimbus3
            - zoo1
            - zoo2
            - zoo3
        links:
            - nimbus1:nimbus
            - nimbus2:nimbus
            - nimbus3:nimbus
            - zoo1:zookeeper
            - zoo2:zookeeper
            - zoo3:zookeeper
        restart: always
        volumes_from:
            - nimbus1
    supervisor2:
        image: storm
        hostname: supervisor2
        container_name: supervisor2
        command: storm supervisor -c nimbus.host=nimbus1,nimbus2,nimbus3
        depends_on:
            - nimbus1
            - nimbus2
            - nimbus3
            - zoo1
            - zoo2
            - zoo3
        links:
            - nimbus1:nimbus
            - nimbus2:nimbus
            - nimbus3:nimbus
            - zoo1:zookeeper
            - zoo2:zookeeper
            - zoo3:zookeeper
        restart: always
        volumes_from:
            - nimbus1
    supervisor3:
        image: storm
        hostname: supervisor3
        container_name: supervisor3
        command: storm supervisor -c nimbus.host=nimbus1,nimbus2,nimbus3
        depends_on:
            - nimbus1
            - nimbus2
            - nimbus3
            - zoo1
            - zoo2
            - zoo3
        links:
            - nimbus1:nimbus
            - nimbus2:nimbus
            - nimbus3:nimbus
            - zoo1:zookeeper
            - zoo2:zookeeper
            - zoo3:zookeeper
        restart: always
        volumes_from:
            - nimbus1

**Comment by silence-liu** [comment]
Is this problem solved?

**Comment by jiucai** [comment]
no, I have not find a way to use this to start storm.

**Comment by 31z4** [comment]
@jiucai I guess you forgot to set zookeeper servers in storm configuration as `storm.zookeeper.servers`. Here is a compose file that worked for me.
```yaml
version: '2'
services:
    zoo1:
        image: zookeeper
        container_name: zoo1
        restart: always
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: zookeeper
        container_name: zoo2
        restart: always
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: zookeeper
        container_name: zoo3
        restart: always
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    nimbus1:
        image: storm
        container_name: nimbus1
        command: storm nimbus -c nimbus.seeds='["nimbus1","nimbus2","nimbus3"]' -c storm.zookeeper.servers='["zoo1","zoo2","zoo3"]'
        depends_on:
            - zoo1
            - zoo2
            - zoo3
        links:
            - zoo1
            - zoo2
            - zoo3
        restart: always

    nimbus2:
        image: storm
        container_name: nimbus2
        command: storm nimbus -c nimbus.seeds='["nimbus1","nimbus2","nimbus3"]' -c storm.zookeeper.servers='["zoo1","zoo2","zoo3"]'
        depends_on:
            - zoo1
            - zoo2
            - zoo3
        links:
            - zoo1
            - zoo2
            - zoo3
        restart: always

    nimbus3:
        image: storm
        container_name: nimbus3
        command: storm nimbus -c nimbus.seeds='["nimbus1","nimbus2","nimbus3"]' -c storm.zookeeper.servers='["zoo1","zoo2","zoo3"]'
        depends_on:
            - zoo1
            - zoo2
            - zoo3
        links:
            - zoo1
            - zoo2
            - zoo3
        restart: always

    supervisor1:
        image: storm
        container_name: supervisor1
        command: storm supervisor -c nimbus.seeds='["nimbus1","nimbus2","nimbus3"]' -c storm.zookeeper.servers='["zoo1","zoo2","zoo3"]'
        depends_on:
            - nimbus1
            - nimbus2
            - nimbus3
            - zoo1
            - zoo2
            - zoo3
        links:
            - nimbus1
            - nimbus2
            - nimbus3
            - zoo1
            - zoo2
            - zoo3
        restart: always

    supervisor2:
        image: storm
        container_name: supervisor2
        command: storm supervisor -c nimbus.seeds='["nimbus1","nimbus2","nimbus3"]' -c storm.zookeeper.servers='["zoo1","zoo2","zoo3"]'
        depends_on:
            - nimbus1
            - nimbus2
            - nimbus3
            - zoo1
            - zoo2
            - zoo3
        links:
            - nimbus1
            - nimbus2
            - nimbus3
            - zoo1
            - zoo2
            - zoo3
        restart: always

    supervisor3:
        image: storm
        container_name: supervisor3
        command: storm supervisor -c nimbus.seeds='["nimbus1","nimbus2","nimbus3"]' -c storm.zookeeper.servers='["zoo1","zoo2","zoo3"]'
        depends_on:
            - nimbus1
            - nimbus2
            - nimbus3
            - zoo1
            - zoo2
            - zoo3
        links:
            - nimbus1
            - nimbus2
            - nimbus3
            - zoo1
            - zoo2
            - zoo3
        restart: always

    ui:
        image: storm
        container_name: ui
        command: storm ui -c nimbus.seeds='["nimbus1","nimbus2","nimbus3"]'
        depends_on:
            - nimbus1
            - nimbus2
            - nimbus3
        links:
            - nimbus1
            - nimbus2
            - nimbus3
        restart: always
        ports:
            - 8080:8080
```
